# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-08-06T15:06:02+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, conint, constr


class DecodePayloadRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    payload: str = Field(
        ...,
        description='Raw Pix BR Code payload string to decode. Its length, emptiness,\nand charset are enforced by the decoder so they map to decoding\nerror codes, not request-shape failures.\n',
    )


class CrcValid(Enum):
    boolean_True = True


class KeyType(Enum):
    cpf = 'cpf'
    cnpj = 'cnpj'
    phone = 'phone'
    email = 'email'
    evp = 'evp'


class Mode(Enum):
    static = 'static'
    dynamic = 'dynamic'


class DecodeErrorCode(Enum):
    DECODING_PAYLOAD_TOO_LONG = 'DECODING_PAYLOAD_TOO_LONG'
    DECODING_INVALID_CHARSET = 'DECODING_INVALID_CHARSET'
    DECODING_MALFORMED_TLV = 'DECODING_MALFORMED_TLV'
    DECODING_CRC_MISMATCH = 'DECODING_CRC_MISMATCH'
    DECODING_MISSING_MANDATORY_FIELD = 'DECODING_MISSING_MANDATORY_FIELD'
    DECODING_UNSUPPORTED_CURRENCY = 'DECODING_UNSUPPORTED_CURRENCY'
    DECODING_INVALID_KEY = 'DECODING_INVALID_KEY'
    DECODING_INVALID_PAYLOAD = 'DECODING_INVALID_PAYLOAD'
    CONTEXT_INVALID_REQUEST = 'CONTEXT_INVALID_REQUEST'


class ProblemDetails(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: AnyUrl
    title: str
    status: conint(ge=400, le=599)
    detail: str
    code: DecodeErrorCode
    correlationId: str


class DecodedInstruction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str | None = Field(
        None,
        description='Recipient Pix key carried by the payload. Present for key-based\ninstructions (static always; dynamic when carried); null when the\ndynamic instruction is location-based.\n',
    )
    key_type: KeyType | None = Field(
        None,
        description='Detected Pix key format. Null when the instruction is location-based.\n',
    )
    location: str | None = Field(
        None,
        description='Dynamic QR location (tag 26.25). Present only for dynamic,\nlocation-based instructions; the raw value is echoed without\nscheme or URL-shape validation. Null for key-based instructions.\n',
    )
    mode: Mode
    amount: constr(pattern=r'^\d{1,10}\.\d{2}$') | None = Field(
        None, description='Optional payment amount with exactly two decimal places.'
    )
    txid: str | None = Field(
        None,
        description='Optional transaction identifier; echoed for static codes when present.',
    )
    description: str | None = Field(
        None,
        description='Optional reference label or description carried by the payload.',
    )
    merchant_name: str
    merchant_city: str
    mcc: str | None = Field(
        None, description='Optional merchant category code; absent when not carried.'
    )
    crc_valid: CrcValid = Field(
        ..., description='Always true; a valid CRC is required for a 200 response.'
    )
